velo:
    resource: "@VeloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

controllers:
    resource: '@VeloBundle/Controller'
    type: annotation

