<?php


namespace VeloBundle\Repository;

/**
 * DisponibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibilityRepository extends \Doctrine\ORM\EntityRepository
{

}