<?php

namespace VeloBundle\Repository\InfoFlowEntity;

/**
 * StoryCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryCommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByIdJoinedToStories($id)
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT s, c
        FROM App\Entity\InfoFlowEntity\StoryComment s
        INNER JOIN c.story  
        WHERE c.id = :id'
        )->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

}
