<?php

namespace VeloBundle\Repository;

/**
 * CommentEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentEventRepository extends \Doctrine\ORM\EntityRepository
{
}
