<?php

namespace VeloBundle\Repository;

/**
 * ConnectorEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectorEventRepository extends \Doctrine\ORM\EntityRepository
{
}
