<?php

namespace VeloBundle\Repository;

/**
 * MarketServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
