<?php

namespace VeloBundle\Repository;

/**
 * NodeEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeEventRepository extends \Doctrine\ORM\EntityRepository
{
}
